version: "3.7"

services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    env_file: mysql_env
    environment:
      TZ: Asia/Seoul
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    # volumes: 에러 ㅠ
